logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
server:
  error:
    include-message: always
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/musiclr}
    username: ${SPRING_DATASOURCE_USERNAME:musiclr}
    password: ${SPRING_DATASOURCE_PASSWORD:musiclr}
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
  session:
    store-type: jdbc
    timeout: 300
  web:
    locale: pt_BR
    locale_resolver: fixed
