create table amizade (id int8 generated by default as identity, data_solicitacao timestamp not null, situacao varchar(255) not null, solicitado_id int8 not null, solicitante_id int8 not null, primary key (id))
create table comentario (id int8 generated by default as identity, data_criacao timestamp not null, texto varchar(255) not null, pessoa_id int8, publicacao_id int8, primary key (id))
create table curtida (id int8 generated by default as identity, pessoa_id int8, publicacao_id int8, primary key (id))
create table permissao (id int8 generated by default as identity, nome varchar(255) not null, usuario_id int8, primary key (id))
create table pessoa (id int8 generated by default as identity, apelido varchar(255), data_nascimento date not null, imagem_perfil oid, nome varchar(255) not null, usuario_id int8 not null, primary key (id))
create table publicacao (id int8 generated by default as identity, audio oid, data_criacao timestamp not null, descricao varchar(255) not null, imagem oid not null, is_publica boolean not null, titulo varchar(255), pessoa_id int8, primary key (id))
create table usuario (id int8 generated by default as identity, email varchar(255) not null, senha varchar(255) not null, primary key (id))

alter table if exists usuario add constraint unique_usuario_email unique (email)
alter table if exists amizade add constraint fk_amizade_solicitado_id foreign key (solicitado_id) references pessoa
alter table if exists amizade add constraint fk_amizade_solicitante_id foreign key (solicitante_id) references pessoa
alter table if exists comentario add constraint fk_comentario_pessoa_id foreign key (pessoa_id) references pessoa
alter table if exists comentario add constraint fk_comentario_publicacao_id foreign key (publicacao_id) references publicacao
alter table if exists curtida add constraint fk_curtida_pessoa_id foreign key (pessoa_id) references pessoa
alter table if exists curtida add constraint fk_curtida_publicacao_id foreign key (publicacao_id) references publicacao
alter table if exists permissao add constraint fk_permissao_usuario_id foreign key (usuario_id) references usuario
alter table if exists pessoa add constraint fk_pessoa_usuario_id foreign key (usuario_id) references usuario
alter table if exists publicacao add constraint fk_publicacao_pessoa_id foreign key (pessoa_id) references pessoa